### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by ameer017** [ameer017/decentralized-resource#7]
https://www.figma.com/design/RavDGYDbBTxLWpWz59jZIg/Decentralized-R.E.S?node-id=5-5087&t=QeKEER8JtKu7JndL-4

**Comment by abskptnyk** [comment]
yo @ameer017, are you willing to assign this issue to me?

**Comment by ameer017** [comment]
Hi Abhishek,
Thanks for your interest but the project is being developed by 3 people and
the issues were created so it can be picked by each developer.

As we look forward to continuing developing the project, I'll gladly reach
out if there are other issues.

Best regards

**Comment by Etz-Hola** [comment]
i will like to work on this
